api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('add_watch/', views.AddWatchView.as_view(), name='api_add_watch'),
]

main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('brands/', views.BrandsView.as_view(), name='brands'),
    path('brands/<str:letter>/', views.BrandsView.as_view(), name='brands'),
    path('brand/<int:id>/', views.BrandView.as_view(), name='brand'),
    path('watch/<int:id>/', views.WatchView.as_view(), name='watch'),
]

timedbase/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include(('main.urls', 'main'), namespace='main')),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    re_path(r'^api-auth/', include('rest_framework.urls'))
]

main/models.py
from django.db import models
from django_countries.fields import CountryField
from utils.strings import super_clean_str
from djmoney.models.fields import MoneyField
from easy_thumbnails.signals import saved_file
from easy_thumbnails.signal_handlers import generate_aliases_global


# generate thumbnails on upload
saved_file.connect(generate_aliases_global)


# Create your models here.
class Brand(models.Model):
    name = models.CharField(max_length=60, unique=True)
    cleaned_name = models.CharField(max_length=60, unique=True)
    country = CountryField(blank=True, null=True)
    url = models.URLField()
    description = models.CharField(max_length=2000, blank=True, null=True)
    logo=models.ImageField(upload_to='brand_logo/', blank=True, null=True)

    def save(self, *args, **kwargs):
        self.cleaned_name = super_clean_str(self.name)
        super(Brand, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


# TODO: fix fields
class Watch(models.Model):
    url = models.URLField(unique=True, blank=True, null=True)
    name = models.CharField(max_length=60)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, related_name="watches", related_query_name="watch")
    reference = models.CharField(max_length=30)
    cleaned_reference = models.CharField(max_length=30)
    description = models.TextField(max_length=2000, blank=True, null=True)

    image = models.ImageField(upload_to='watch_image/', blank=True, null=True)

    origin = models.CharField(max_length=30, null=True, blank=True)
    gender = models.CharField(max_length=30, null=True, blank=True)
    collection = models.CharField(max_length=80, null=True, blank=True)
    water_resistance = models.CharField(max_length=80, null=True, blank=True)
    case_shape = models.CharField(max_length=80, null=True, blank=True)
    case_diameter = models.CharField(max_length=80, null=True, blank=True)
    case_width = models.CharField(max_length=80, null=True, blank=True)
    case_length = models.CharField(max_length=80, null=True, blank=True)
    case_thickness = models.CharField(max_length=80, null=True, blank=True)
    case_back = models.CharField(max_length=80, null=True, blank=True)
    crystal = models.CharField(max_length=80, null=True, blank=True)
    case_material = models.CharField(max_length=80, null=True, blank=True)
    bezel_material = models.CharField(max_length=80, null=True, blank=True)
    weight = models.CharField(max_length=80, null=True, blank=True)
    lugs_width = models.CharField(max_length=80, null=True, blank=True)
    movement_type = models.CharField(max_length=80, null=True, blank=True)
    caliber_diameter = models.CharField(max_length=80, null=True, blank=True)
    movement_model = models.CharField(max_length=80, null=True, blank=True)
    jewels = models.CharField(max_length=80, null=True, blank=True)
    time = models.CharField(max_length=80, null=True, blank=True)
    caliber = models.CharField(max_length=80, null=True, blank=True)
    battery = models.CharField(max_length=80, null=True, blank=True)
    functions = models.CharField(max_length=80, null=True, blank=True)
    dial_color = models.CharField(max_length=80, null=True, blank=True)
    indexes = models.CharField(max_length=80, null=True, blank=True)
    strap_material = models.CharField(max_length=80, null=True, blank=True)
    buckle = models.CharField(max_length=80, null=True, blank=True)
    strap_color = models.CharField(max_length=80, null=True, blank=True)
    features = models.CharField(max_length=80, null=True, blank=True)

    def __str__(self):
        return "{} {}".format(self.name, self.reference)

    def save(self, *args, **kwargs):
        self.cleaned_reference = super_clean_str(self.reference)

        super(Watch, self).save(*args, **kwargs)

    class Meta:
        unique_together = [['brand', 'cleaned_reference'], ['brand', 'reference']]
        verbose_name_plural = "watches"


class Price(models.Model):
    price = MoneyField(max_digits=14, decimal_places=2, default_currency='USD')
    url = models.URLField()
    store = models.ForeignKey("main.Store", on_delete=models.CASCADE)
    watch = models.ForeignKey("main.Watch", on_delete=models.CASCADE, related_name="prices", related_query_name="price")
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return "{} timestamp:{}".format(self.watch.cleaned_reference, self.timestamp)


class Store(models.Model):
    name = models.CharField(max_length=60, unique=True)
    url = models.URLField(unique=True)
    cleaned_name = models.CharField(max_length=60, unique=True)

    def save(self, *args, **kwargs):
        self.cleaned_name = super_clean_str(self.name)

        super(Store, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

main/views.py
from django.shortcuts import render, get_object_or_404
from .models import Brand, Watch, Price, Store
from django.db.models.functions import Substr
from django.db.models import Count
import string
from django.views import View
from django.db.models import OuterRef, Subquery, Exists
from django.forms.models import model_to_dict

# Create your views here.

class IndexView(View):
    def get(self, request):
        # TODO: Better home page
        return render(request, 'main/index.html')


class BrandsView(View):
    def get (self, request, letter=None):
        count_letters_queryset = []
        if not letter:
            brands = Brand.objects.order_by('?')[0:10]
        else:
            brands = Brand.objects.filter(cleaned_name__startswith=letter)

        available_alphabet = Brand.objects.all().annotate(first_letter=Substr('cleaned_name', 1, 1)).values_list("first_letter", flat=True).distinct()
        # available_brands = count_letters_queryset[0].union(*count_letters_queryset[1:])

        return render(request, 'main/brands.html', {'brands': brands, 'available_alphabet': available_alphabet, 'alphabet': string.ascii_lowercase, 'active_letter': letter})


class BrandView(View):
    def get(self, request, id):
        brand = get_object_or_404(Brand, pk=id)

        return render(request, 'main/brand.html', {'brand': brand})


class WatchView(View):
    def get(self, request, id):
        watch = get_object_or_404(Watch, pk=id)

        watch_details = model_to_dict(watch)
        del watch_details['name']
        del watch_details['url']
        del watch_details['image']
        del watch_details['description']
        del watch_details['id']
        del watch_details['cleaned_reference']
        del watch_details['brand']

        prices = Price.objects.filter(watch=watch).order_by('store', '-timestamp').distinct('store')

        return render(request, 'main/watch.html', {'watch': watch, 'prices': prices, 'watch_details': watch_details})

main/templates/main/brand.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ brand.name }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="e-shadow p-3 mb-5 mt-2 bg-white rounded" style="">
                    {% if brand.logo %}
                        <img src="{{ brand.logo.url }}" class="img-fluid" alt="{{ brand.name }}">
                    {% else %}
                        <img src="{% static "images/defaultbrand.png" %}" class="img-fluid" alt="{{ brand.name }}">
                    {% endif %}
                    <h2>{{ brand.name }}</h2>
                    <p>{{ brand.description }}</p>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
                <div class="row">
                    {% for watch in brand.watches.all %}
                        <div class="col-2 d-flex align-items-stretch justify-content-center">
                            {% include "main/components/watch.html" %}
                        </div>
                    {% endfor %}
                </div>
                </div>
{% endblock %}

main/templates/main/brands.html
{% extends "base.html" %}
{% load static %}

{% block title %}Brands{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
        <div class="col">
            <div class="jumbotron text-center rounded-0 rounded-bottom">
            {% for l in alphabet%}
                {% if l == active_letter %}
                    <a href="{% url 'main:brands' l%}" class="btn btn-primary disabled" role="button" aria-disabled="true">{{ l }}</a>
                {% elif l in available_alphabet %}
                    <a href="{% url 'main:brands' l%}" class="btn btn-link" role="button">{{ l }}</a>
                {% else %}
                    <a href="{% url 'main:brands' l%}" class="btn btn-link disabled" role="button" aria-disabled="true">{{ l }}</a>
                {% endif %}
            {% endfor %}
            </div>
            <div class="row px-2">
                {% for brand in brands %}
                <div class="col-2 d-flex align-items-stretch justify-content-center">
                    {% include "main/components/brand.html" %}
                </div>
                {% endfor %}
            </div>
        </div>
        </div>
    </div>
{% endblock %}

main/templates/main/index.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
        <div class="col">
            <h1>Featured watch:</h1>
        </div>
        </div>
    </div>
{% endblock %}

main/templates/main/watch.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block title %}{{ watch.name }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="e-shadow p-3 mb-5 mt-2 bg-white rounded" style="">
                    {% if watch.image %}
                        <img src="{{ watch.image.url }}" class="img-fluid" alt="{{ watch.name }}">
                    {% else %}
                        <img src="{% static "images/defaultbrand.png" %}" class="img-fluid" alt="{{ watch.name }}">
                    {% endif %}
                    <h2><a href="{{ watch.url }}" target="_blank">{{ watch.name }}</a></h2>
                    <p>{{ watch.description }}</p>
                    <table class="table table-sm table-hover">
                        <tbody>
                            {% for key, value in watch_details.items %}
                                {% if value %}
                                    <tr>
                                        <th>{{ key }}</th>
                                        <td>{{ value }}</td>
                                    </tr>
                                {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="e-shadow p-3 mb-5 mt-2 bg-white rounded" style="">
                    <h2>Offers:</h2>
                    {% for sale in prices %}
                    <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ sale.store.name }}</h5>
                        <p class="card-text"><b class="text-success">{{ sale.price }}</b><p> updated: {{ sale.timestamp|naturaltime }} </p></p>
                        <a href="{{ sale.url }}" class="btn btn-primary" target="_blank">See offer</a>
                    </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}